### ISSUE TITLE
Zipf law

### ISSUE THREAD

**Issue by krober10nd** [nschloe/gh-stars#9]
I wonder if the stars frequency follows the zipf law. 

https://simple.m.wikipedia.org/wiki/Zipf%27s_law

**Comment by nschloe** [comment]
I don't quite understand.

**Comment by krober10nd** [comment]
'Zipf's law states that given a large sample of words used, the frequency of any word is inversely proportional to its rank in the frequency table. So word number n has a frequency proportional to 1/n.'

occurs in almost every statistic (not just words).

**Comment by krober10nd** [comment]
If you receive x stars per day, then the frequency of those days where you receive x stars should be proportional to 1/n where n is the ordered rank of that day.

**Comment by nschloe** [comment]
Ah. Well, that'd be hard to find out with GitHub's API. You cannot find how many stars where given in a particular time frame, but rather at what time the `n`th star was given. You could then bisect your way through to the days, but yeah, I won't do it. :)

**Comment by krober10nd** [comment]
hah oh well. just a cool thing that happens throughout nature. Any time someone starts counting something, it basically follows this law. if it doesn't something it's a good signal something is abnormal.
